### ISSUE TITLE
No attribute 'field_ises' for a MixedSet

### ISSUE THREAD

**Issue by ctjacobs** [OP2/PyOP2#429]
I've just updated PyOP2 (and petsc, firedrake, ffc, etc) and I'm now getting the following error:

```
Traceback (most recent call last):
  File "../../firedrake_fluids/shallow_water.py", line 834, in <module>
    solution = sw.run(dc, annotate=True)
  File "../../firedrake_fluids/shallow_water.py", line 695, in run
    solver = NonlinearVariationalSolver(problem, solver_parameters=solver_parameters)
  File "/data/dolfin-adjoint-ctjacobs/dolfin_adjoint/compatibility.py", line 16, in nvs_init
    backend.NonlinearVariationalSolver.__init__(self, problem, solver_parameters)
  File "/data/firedrake/firedrake/variational_solver.py", line 249, in __init__
    ctx.set_jacobian(self.snes)
  File "/data/firedrake/firedrake/variational_solver.py", line 104, in set_jacobian
    snes.setJacobian(self.form_jacobian, J=self._jac._M.handle,
  File "/usr/local/lib/python2.7/dist-packages/PyOP2-0.11.0_172_g49bc168_dirty-py2.7-linux-x86_64.egg/pyop2/petsc_base.py", line 489, in handle
    self._init()
  File "/usr/local/lib/python2.7/dist-packages/PyOP2-0.11.0_172_g49bc168_dirty-py2.7-linux-x86_64.egg/pyop2/petsc_base.py", line 271, in _init
    self._init_nest()
  File "/usr/local/lib/python2.7/dist-packages/PyOP2-0.11.0_172_g49bc168_dirty-py2.7-linux-x86_64.egg/pyop2/petsc_base.py", line 288, in _init_nest
    isrows=rset.field_ises, iscols=cset.field_ises)
  File "/usr/local/lib/python2.7/dist-packages/PyOP2-0.11.0_172_g49bc168_dirty-py2.7-linux-x86_64.egg/pyop2/base.py", line 1039, in __getattr__
    return getattr(self.set, name)
AttributeError: 'MixedSet' object has no attribute 'field_ises'
```

This only seems to happen when running with firedrake-adjoint. I'll try to come up with a minimal failing example soon.

**Comment by wence-** [comment]
Something very strange is going on here.  rest and cset at this point /should not/ be MixedDataSets (you're inside the initialisation of the blocks in a mixed matrix).

**Comment by wence-** [comment]
Oh sorry, ignore me.

**Comment by wence-** [comment]
what does type(rset) return?

**Comment by ctjacobs** [comment]
`<class 'pyop2.base.MixedDataSet'>`

**Comment by ctjacobs** [comment]
And the same for `cset`.

**Comment by wence-** [comment]
So that really ought to be a `pyop2.petsc_base.MixedDataSet`

**Comment by ctjacobs** [comment]
The following example fails:

```
from firedrake import *
from firedrake_adjoint import *

mesh = UnitSquareMesh(1, 1)
U = VectorFunctionSpace(mesh, "CG", 2)
H = FunctionSpace(mesh, "CG", 1)
W = MixedFunctionSpace([U, H])

solution_old = Function(W).interpolate(Expression(("1e-16", "1e-16", "sin(x[1])")))
solution = Function(W)
u, h = split(solution)
w, v = TestFunctions(W)
u_old, h_old = split(solution_old)

F = (inner(w, u) - inner(w, u_old))*dx - inner(v, div(h*u))*dx
    
solve(F == 0, solution)
```

but if I run it without `from firedrake_adjoint import *`, the solve succeeds. So firedrake-adjoint might be doing something strange under the hood. I can't replicate this problem in a Firedrake-only setup.

**Comment by ctjacobs** [comment]
So I added the following 2 print statements

```
        print type(test.function_space().dof_dset)
        print type(trial.function_space().dof_dset)
```

above `test, trial = f.arguments()` in `firedrake/assemble.py`. This gives

```
<class 'pyop2.base.MixedDataSet'>
<class 'pyop2.base.MixedDataSet'>
```

But if I add `print type(solution.function_space().dof_dset)` just before `solve(F == 0, solution)` in the failing example, this changes to the expected type:

```
<class 'pyop2.petsc_base.MixedDataSet'>
<class 'pyop2.petsc_base.MixedDataSet'>
```

**Comment by wence-** [comment]
I think I fixed this in PyOP2 master, please update and try again.

**Comment by ctjacobs** [comment]
Works for me - thanks!
